### ISSUE TITLE
toUnsigned should be asUnsigned in docs

### ISSUE THREAD

**Issue by kquick** [GaloisInc/bv-sized#4]
https://github.com/GaloisInc/bv-sized/blob/6c2f3a925edc1f82b38df2e32b0bdf762ec10171/src/Data/BitVector/Sized.hs#L111

looks like a name change update.

**Comment by benjaminselfridge** [comment]
Thanks! Fixed by https://github.com/GaloisInc/bv-sized/commit/3e057db152fe0ffe8d549ef610cfc91efdeb5a70.
